name: myblog
services:
  mysql:
    container_name: pmysql
    image: mysql:8.0.23
    ports: 
      - "3307:3306"
    environment:
      - MYSQL_ROOT_PASSWORD=123456
      - MYSQL_DATABASE=wordpress
    volumes:
      - mysql-data:/var/lib/mysql
      - /home/rkwork/work_place/project/docker_volume/wordpress/mysql:/etc/mysql/conf.d
    restart: always
    networks:
      - rknet
  
  wordpress:
    container_name: wordpress
    image: wordpress:latest
    ports: 
      - "8082:80"
    environment: 
      WORDPRESS_DB_HOST: pmysql
      WORDPRESS_DB_USER: root
      WORDPRESS_DB_PASSWORD: 123456
      WORDPRESS_DB_NAME: wordpress
    volumes:
      - wordpress:/var/www/html
    restart: always
    networks:
      - rknet
    depends_on:
      - mysql

volumes:
  mysql-data:
  wordpress:

networks:
  rknet:
  